@url = http://localhost:3001/api/whiteboard

POST {{url}}
Content-Type: application/json

{
  "creator": "Madina",
  "whiteboard": {
    "name": "Madina's protected whiteboard",
    "password": "secret"
  }
}
###
###

DELETE {{url}}/6c3121aa324e
Authorization: bearer
###

GET {{url}}/is-protected/62f55e0ba428a

###
GET {{url}}/62325fa249d89e
Authorization: bearer 

###
POST {{url}}/request-to-join/623260e6f48a
Content-Type: application/json

{
  "name": "Mavjuda",
  "password": "secret"
}

###

###
POST {{url}}/process-request-to-join
Authorization: bearer
Content-Type: application/json

{
  "whiteboardId": "6232e028a",
  "userId": "6232a40",
  "decision": false
}