@url = http://localhost:3000/whiteboard

POST {{url}}
Content-Type: application/json

{
  "creator": "Alisher",
  "session": {}
}

###

DELETE {{url}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoYXNoZWRIb3N0SWQiOiIkMmIkMTEkQjRicFhLNFhXTHdVUXZzaTZkRWpTZWhzOUxSTmVzUVIvN1BaNFBjdDJsd0JMWFJOZThhdkMiLCJoYXNoZWRTZXNzaW9uSWQiOiIkMmIkMTEkR2ouVk1NZXp2d20wallmMi9jNWZkdVp5V2NYdlRLbTZXb0pXa3RwVWNLRmdxYVYwTnV1OWUiLCJpYXQiOjE2NDcyOTkxNzR9.rlczhrsIz3cx5bGlaHz2qR33guqFMCZXUZp5x3ZPdA4
